version: "3.7"


services:

  item-app:
    image: richo3673/item-app:v1
    ports:
      - 801:8080
    working_dir: /app
    environment:
      NODE_ENV: production
      DB_HOST: item-db
    volumes:
      - ./:/app
    depends_on:
      - item-db

  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db

volumes:
  app-db: